Repository AY2324S2-CS2103T-T08-3/tp, pull requests merged in 2024-04, with the labels that each got.

#66 Add FilterSalaryCommand
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterSalaryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterSalaryCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/model/person/SalaryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/SalaryRange.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterSalaryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterSalaryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/SalaryContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/SalaryRangeTest.java
Labels: enhancement

#59 FilterTag feature
  src/main/java/seedu/address/logic/commands/FilterSalaryCommand.java
  src/main/java/seedu/address/logic/commands/FilterTagCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterTagCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FilterSalaryCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterTagCommandParserTest.java
  src/test/java/seedu/address/model/person/CompanyNameTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#72 Fix EditCompanyName bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/CompanyName.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/CompanyNameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: bug

#74 Filter contact list based on interview date and time feature
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterInterviewTimeCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterInterviewTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterTagCommandParser.java
  src/main/java/seedu/address/model/person/InterviewTime.java
  src/main/java/seedu/address/model/person/InterviewTimeContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FilterInterviewTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterSalaryCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/person/InterviewTimeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/InterviewTimeTest.java
Labels: enhancement

#88 Update UG
  docs/UserGuide.md
Labels: documentation

#90 Improve on UG
  docs/UserGuide.md
Labels: documentation

#166 Fix error and success messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterInterviewTimeCommand.java
Labels: bug

#167 Fix logic bugs of FilterCommand classes
  src/main/java/seedu/address/logic/parser/FilterInterviewTimeCommandParser.java
  src/main/java/seedu/address/model/person/InterviewTime.java
  src/test/java/seedu/address/model/person/InterviewTimeTest.java
Labels: bug

#174 Update UG with new screenshot
  docs/UserGuide.md
  docs/images/FindExample.png
Labels: documentation

#178 Resolve bug for delete tag command
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
Labels: bug

#172 fix interviewtime not optional
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/InterviewTime.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/InterviewTimeTest.java
Labels: bug

#180 fix add resume feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddResumeCommandParser.java
  src/main/java/seedu/address/model/person/user/User.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResumeWindow.java
  src/test/java/seedu/address/logic/parser/AddResumeCommandParserTest.java
Labels: bug

#179 Update delete tag feature in UG
  docs/UserGuide.md
Labels: documentation

#194 Uml update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UserDiagram.puml
  docs/images/UiClassDiagram2.png
  docs/images/UserDiagram.png
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddResumeCommandParser.java
  src/main/java/seedu/address/model/person/Info.java
Labels: bug, documentation

#204 Fix delete tag bug
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
Labels: bug
